name: pytorch_gpu
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - flask
  - numpy
  - pydub
  - requests
  - pytorch=2.5.1
  - torchvision
  - torchaudio
  - cudatoolkit=11.7
  - pip:
      - pyannote.audio
      - whisper
      - tempfile
